#!/bin/bash

read -p "Ajouter la date de verification dans le suivi ? (y/[n]) ?" yn < /dev/tty
yn=${yn:n}
case $yn in
 [Yy]* )
 echo commit vérifié le `date`>>suivi/suivi.txt
 git add suivi/suivi.txt
 exit 0;;
 [Nn]* )
 exit 0;;
esac
exit 0